### ISSUE TITLE
Investigate portal optimization

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_portal8#40]
- Render only changed content?
  - More efficient macro detection
  - Investigate using Werkzeug for routing
  - Optimize space loading

**Comment by ahussein** [comment]
Results of Investigations related to using Werkzeug for routing:
There is no point of using the routing component of Werkzeug while maintaining the current page processor. From my tests, we end up with creating URL maps for Werkzeug and custom endpoints since almost each path is manipulated and some extra params are created before passing to the pageprocessor.
Example:

```
if path.find("jslib/") == 0:
            path = path[6:]
            user = "None"
            # self.pageprocessor.log(ctx, user, path)
            return self.pageprocessor.processor_page(environ, start_response, self.jslibroot, path, prefix="jslib/")

        if path.find("images/") == 0:
            space, image = pathparts[1:3]
            spaceObject = self.getSpace(space)
            image = image.lower()

            if image in spaceObject.docprocessor.images:
                path2 = j.tools.path.get(spaceObject.docprocessor.images[image])

                return self.pageprocessor.processor_page(
                    environ, start_response, path2.dirname(), path2.basename(), prefix="images")
            ctx.start_response('404', [])
```

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_portal8/pull/90
